// @ts-check

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 自動生成側邊欄
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.'  // '.' 表示從 docs 目錄開始
    }
  ]
};

export default sidebars;
