site_url: https://docs.ccnda.org
display_url: https://docs.ccnda.org

# 繁中
locale: zh_Hant

# 登入介面 logo
logo_url: /img/logo2.png

backend:
  name: github
  repo: ccnda/docs.ccnda.org
  branch: main

local_backend: true

media_folder: "static/uploads"
public_folder: "/uploads"

# 新增全域編輯器提示訊息
editor:
  preview: true

collections:
  - name: docs
    label: "API 文件"
    folder: docs
    create: true
    slug: "{{slug}}"
    preview_path: "docs/{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { 
          label: "選單排序 (數字小的排前面，留空會排在最後)",
          name: "sidebar_position",
          widget: "number",
          value_type: "int",
          min: 1,
          default: 10, 
          required: false
        }
      - {
          label: "標籤",
          name: "tags",
          widget: "list",
          required: false,
          hint: "可輸入多個標籤，按 Enter 分隔"
        }
      - { label: "SEO 描述", name: "description", widget: "text", required: false }
      - { label: "內文", name: "body", widget: "markdown" }
    sortable_fields: ["title", "sidebar_position"]
